### PR TITLE
Made check pwd job time insensitive

### LINKED ISSUE #579: [FEATURE]: Make CheckPasswordsJob time-insensitive
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **feature request** for _one_ feature, not a question, discussion or multiple features.
- [X] This is not a feature request for the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This feature is **not** already requested on Github _(I've searched it)_.
- [X] This feature does not already exist _(I checked the [wiki](https://git.mdns.eu/nextcloud/passwords/-/wikis/home))_.

### Current Status

- CheckPasswordsJob is time sensitive as by default all `TimedJob`s are time-sensitive 

### Feature Description

- It isn't a time sensitive operation, just needs to run once a day
- Just need to add a `$this->setTimeSensitivity(self::TIME_INSENSITIVE);` to the job class constructor

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by akhil1508**
Resolves https://github.com/marius-wieschollek/passwords/issues/579

### CODE REVIEW

**Comment by marius-wieschollek** [comment]
Have you tested this? Because the `OC\BackgroundJob\TimedJob` doesn't provide this function. We need to switch to `OCP\BackgroundJob\TimedJob` for this.

Also please sign your commits as required, see [Verify Git Commits](https://git.mdns.eu/nextcloud/passwords/-/wikis/Developers/Contributing/Verify-Git-Commits).

**Comment by akhil1508** [comment]
> Have you tested this? Because the OC\BackgroundJob\TimedJob doesn't provide this function. We need to switch to OCP\BackgroundJob\TimedJob for this.

Makes sense. My bad, I thought a small enough change and didn't really test it out. Didn't notice that. Let me check the nextcloud source code to see if these two classes are very different functionality wise.

> Also please sign your commits as required, see [Verify Git Commits](https://git.mdns.eu/nextcloud/passwords/-/wikis/Developers/Contributing/Verify-Git-Commits).

Done

**Comment by akhil1508** [comment]
@marius-wieschollek It looks fine to just make the switch to `OCP\BackgroundJob\TimedJob;`. The other one is a deprecated class for "internal use" as per a comment.

**Comment by marius-wieschollek** [comment]
Now i get an error show for the $interval variable. This is defined hardcoded in line 41 and overwritten in SendServerSurvey, CheckNightlyUpdates and CheckPasswordsJob. Also there seems to be a dependency to `ITimeFactory $time` in the constructor of the Job class which isn't fulfilled because the constructor isn't called and the AbstractTimedJob (and all that extend it) don't require it.

**Comment by akhil1508** [comment]
> Now i get an error show for the $interval variable. This is defined hardcoded in line 41 and overwritten in SendServerSurvey, CheckNightlyUpdates and CheckPasswordsJob. Also there seems to be a dependency to ITimeFactory $time in the constructor of the Job class which isn't fulfilled because the constructor isn't called and the AbstractTimedJob (and all that extend it) don't require it.

@marius-wieschollek Got it, I'll check on how to make it compatible correctly and actually run it and test.. My bad on assuming it "should" work out of the box, sorry :(

**Pull request closed without merging**
