### PR TITLE
fix: use LoginCredentials\IStore instead of accessing session directly

### LINKED ISSUE #683: [BUG]: Unable to verify user on 30.0.2 RC1
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "30.0.2.0",
        "app": "2024.11.20-build5581",
        "lsr": false,
        "php": "8.3.6",
        "cronPhp": "8.3.6"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": false,
        "subdirectory": false
    },
    "services": {
        "images": "imaginary",
        "favicons": "default",
        "previews": "default",
        "security": "hibp",
        "words": "auto",
        "previewApi": false,
        "faviconApi": false
    },
    "settings": {
        "channel": "beta",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "status": {
        "autoBackupRestored": false
    },
    "apps": {
        "guests": {
            "installed": true,
            "enabled": true
        },
        "occweb": {
            "installed": false,
            "enabled": false
        },
        "theming": {
            "installed": false,
            "enabled": false
        },
        "passman": {
            "installed": false,
            "enabled": false
        },
        "unsplash": {
            "installed": false,
            "enabled": false
        },
        "impersonate": {
            "installed": false,
            "enabled": false
        },
        "passwords_handbook": {
            "installed": false,
            "enabled": false
        }
    },
    "sharing": {
        "shares": 10
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```
```


### Client Information

unrelated


### Bug description

With 30.0.2 RC1, passwords cause a 500 on, for example, dashboard and the admin settings page, and passwords itself obviously.  `Login attempt with invalid session for $USERID` and `Unable to verify user $USERID` are logged (full log see below). 

The root cause it that passwords directly looks up the `login_credentials` information from the session instead of using the API provided by `OCP\Authentication\LoginCredentials\IStore`. And its format has changed in https://github.com/nextcloud/server/pull/48939



### Steps to reproduce

1. Update to 30.0.2 RC1 (beta channel)
2. Open Dashboard, or admin settings, or passwords itself
3. see the internal error page

### Expected behavior

1. It continues to work as before

### Nextcloud Logs

```shell
{
  "reqId": "QvZuldoTfZWiuCbwNnKN",
  "level": 2,
  "time": "2024-11-01T08:52:29+00:00",
  "remoteAddr": "REDACTED",
  "user": "$USERID",
  "app": "passwords",
  "method": "GET",
  "url": "/settings/admin/overview",
  "message": "Login attempt with invalid session for $USERID",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0",
  "version": "30.0.2.0",
  "data": {
    "app": "passwords"
  }
}
{
  "reqId": "QvZuldoTfZWiuCbwNnKN",
  "level": 3,
  "time": "2024-11-01T08:52:29+00:00",
  "remoteAddr": "REDACTED",
  "user": "$USERID",
  "app": "index",
  "method": "GET",
  "url": "/settings/admin/overview",
  "message": "Unable to verify user $USERID",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0",
  "version": "30.0.2.0",
  "exception": {
    "Exception": "Exception",
    "Message": "Unable to verify user $USERID",
    "Code": 0,
    "Trace": [
      {
        "file": "/path/to/nextcloud/apps/passwords/lib/Services/EnvironmentService.php",
        "line": 361,
        "function": "loadUserInformation",
        "class": "OCA\\Passwords\\Services\\EnvironmentService",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/apps/passwords/lib/Services/EnvironmentService.php",
        "line": 185,
        "function": "determineAppMode",
        "class": "OCA\\Passwords\\Services\\EnvironmentService",
        "type": "->"
      },
      {
        "function": "__construct",
        "class": "OCA\\Passwords\\Services\\EnvironmentService",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 61,
        "function": "newInstanceArgs",
        "class": "ReflectionClass",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 106,
        "function": "buildClass",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 124,
        "function": "resolve",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php",
        "line": 448,
        "function": "query",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php",
        "line": 420,
        "function": "queryNoFallback",
        "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 74,
        "function": "query",
        "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
        "type": "->"
      },
      {
        "function": "OC\\AppFramework\\Utility\\{closure}",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 61,
        "function": "array_map"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 106,
        "function": "buildClass",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 124,
        "function": "resolve",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php",
        "line": 448,
        "function": "query",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php",
        "line": 420,
        "function": "queryNoFallback",
        "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 74,
        "function": "query",
        "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
        "type": "->"
      },
      {
        "function": "OC\\AppFramework\\Utility\\{closure}",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 61,
        "function": "array_map"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 106,
        "function": "buildClass",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 124,
        "function": "resolve",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php",
        "line": 448,
        "function": "query",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/ServerContainer.php",
        "line": 137,
        "function": "queryNoFallback",
        "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 42,
        "function": "query",
        "class": "OC\\ServerContainer",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/Settings/Manager.php",
        "line": 175,
        "function": "get",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/Settings/Manager.php",
        "line": 323,
        "function": "getSettings",
        "class": "OC\\Settings\\Manager",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php",
        "line": 70,
        "function": "getAllowedAdminSettings",
        "class": "OC\\Settings\\Manager",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php",
        "line": 105,
        "function": "formatSections",
        "class": "OCA\\Settings\\Controller\\AdminSettingsController",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php",
        "line": 55,
        "function": "formatAdminSections",
        "class": "OCA\\Settings\\Controller\\AdminSettingsController",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php",
        "line": 141,
        "function": "getNavigationParameters",
        "class": "OCA\\Settings\\Controller\\AdminSettingsController",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php",
        "line": 58,
        "function": "getIndexResponse",
        "class": "OCA\\Settings\\Controller\\AdminSettingsController",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 208,
        "function": "index",
        "class": "OCA\\Settings\\Controller\\AdminSettingsController",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 114,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/AppFramework/App.php",
        "line": 161,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/path/to/nextcloud/lib/base.php",
        "line": 1001,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/path/to/nextcloud/index.php",
        "line": 24,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/path/to/nextcloud/apps/passwords/lib/Services/EnvironmentService.php",
    "Line": 398,
    "message": "Unable to verify user $USERID",
    "exception": {},
    "CustomMessage": "Unable to verify user $USERID"
  }
}
```
```


### Browser Logs

_No response_

### PR DESCRIPTION
**Pull request by blizzz**
fixes https://github.com/marius-wieschollek/passwords/issues/683

did some smoke test on my personal instance, and is looking good there.

### CODE REVIEW

**Comment by blizzz** [comment]
cc @marius-wieschollek

**Review by frake65 — APPROVED** [review]
looks good for me.

**Comment by AlexBreedveld** [comment]
This needs to be merged ASAP, as the bug fixed by this pull prevents users from using any Nextcloud app, even the dashboard in the latest NC server version (30.0.2.0).

**Review by AlexBreedveld — APPROVED** [review]
can confirm it fixes #683 on my instance. Code looks good

**Comment by kylespencer** [comment]
What's the best way to apply this to an instance?

**Comment by blizzz** [comment]
> What's the best way to apply this to an instance?

```
wget https://patch-diff.githubusercontent.com/raw/marius-wieschollek/passwords/pull/684.patch
cd /path/to/nextcloud/apps/passwords
patch -p1 < /path/to/684.patch
```

cf. https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html#patching-apps

**Comment by mpractic** [comment]
Thanks for being so fast in finding a fix!

**Review by mpractic — APPROVED** [review]
It fixes the issue.

**Review by marius-wieschollek — APPROVED** [review]

**Comment by joergmschulz** [comment]
sorry, this patch doesn't help in an installation where OIDC is the only login method. Disabling passwords on that (test) environment again.

**Comment by coharms** [comment]
> > What's the best way to apply this to an instance?
> 
> ```
> wget https://patch-diff.githubusercontent.com/raw/marius-wieschollek/passwords/pull/684.patch
> cd /path/to/nextcloud/apps/passwords
> patch -p1 < /path/to/684.patch
> ```
> 
> cf. https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html#patching-apps

Just as an addition, when getting asked which file to patch just add the path to _EnvironmentService.php_ which should be located under _lib/Services/EnvironmentService.php_ as it is the file to be patched.

**Pull request merged**
